#include "reduct/inst.h"
#include <stdint.h>

const uint16_t reductOpcodeFlags[UINT8_MAX + 1] = {
    [REDUCT_OPCODE_LIST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_RANGE,
    [REDUCT_OPCODE_JMP] = REDUCT_OP_FLAG_IS_JUMP | REDUCT_OP_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_JMPF] = REDUCT_OP_FLAG_IS_JUMP | REDUCT_OP_FLAG_READ_A,
    [REDUCT_OPCODE_JMPT] = REDUCT_OP_FLAG_IS_JUMP | REDUCT_OP_FLAG_READ_A,
    [REDUCT_OPCODE_CALL] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_READ_RANGE | REDUCT_OP_FLAG_IS_CALL,
    [REDUCT_OPCODE_CALL_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_READ_RANGE | REDUCT_OP_FLAG_IS_CALL,
    [REDUCT_OPCODE_MOV] =
        REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_MOV_CONST] =
        REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_RET] = REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_RET_CONST] = REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_EQ] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_EQ_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_NEQ] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_NEQ_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_LT] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_LT_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_LE] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_LE_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_GT] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_GT_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_GE] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_GE_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_ADD] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_ADD_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_SUB] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_SUB_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_MUL] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_MUL_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_DIV] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_DIV_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_MOD] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_MOD_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_BAND] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BAND_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BOR] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BOR_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BXOR] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BXOR_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE | REDUCT_OP_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BNOT] =
        REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_BNOT_CONST] =
        REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_SHL] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_SHL_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_SHR] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_SHR_CONST] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_B |
        REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_PURE,
    [REDUCT_OPCODE_CLOSURE] = REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_READ_C,
    [REDUCT_OPCODE_NOP] = 0,
    [REDUCT_OPCODE_CAPTURE] = REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C,
    [REDUCT_OPCODE_CAPTURE_CONST] = REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C,
    [REDUCT_OPCODE_TAILCALL] = REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C |
        REDUCT_OP_FLAG_READ_RANGE | REDUCT_OP_FLAG_IS_CALL | REDUCT_OP_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_TAILCALL_CONST] = REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C |
        REDUCT_OP_FLAG_READ_RANGE | REDUCT_OP_FLAG_IS_CALL | REDUCT_OP_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_JEQ] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JEQ_CONST] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JNEQ] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JNEQ_CONST] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JLT] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JLT_CONST] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JLE] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JLE_CONST] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JGT] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JGT_CONST] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JGE] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JGE_CONST] =
        REDUCT_OP_FLAG_HAS_CONST | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_C | REDUCT_OP_FLAG_IS_SKIP,
    [REDUCT_OPCODE_RECUR] =
        REDUCT_OP_FLAG_HAS_TARGET | REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_RANGE | REDUCT_OP_FLAG_IS_CALL,
    [REDUCT_OPCODE_TAILRECUR] =
        REDUCT_OP_FLAG_READ_A | REDUCT_OP_FLAG_READ_RANGE | REDUCT_OP_FLAG_IS_CALL | REDUCT_OP_FLAG_IS_TERMINATOR,
};