#include <reduct/opcode.h>

const uint16_t reduct_opcode_flags[UINT8_MAX + 1] = {
    [REDUCT_OPCODE_NOP] = 0,
    [REDUCT_OPCODE_MOV] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_LIST] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_RANGE,
    [REDUCT_OPCODE_CLOSURE] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_CAPTURE] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_JMP] = REDUCT_OPCODE_FLAG_IS_JUMP | REDUCT_OPCODE_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_JMPF] = REDUCT_OPCODE_FLAG_IS_JUMP | REDUCT_OPCODE_FLAG_READ_A,
    [REDUCT_OPCODE_JMPT] = REDUCT_OPCODE_FLAG_IS_JUMP | REDUCT_OPCODE_FLAG_READ_A,
    [REDUCT_OPCODE_CALL] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_READ_RANGE | REDUCT_OPCODE_FLAG_IS_CALL,
    [REDUCT_OPCODE_RET] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_TAILCALL] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
        REDUCT_OPCODE_FLAG_READ_RANGE | REDUCT_OPCODE_FLAG_IS_CALL | REDUCT_OPCODE_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_RECUR] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_RANGE |
        REDUCT_OPCODE_FLAG_IS_CALL,
    [REDUCT_OPCODE_TAILRECUR] = REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_RANGE | REDUCT_OPCODE_FLAG_IS_CALL |
        REDUCT_OPCODE_FLAG_IS_TERMINATOR,
    [REDUCT_OPCODE_EQ] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_NEQ] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_LT] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_LE] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_GT] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_GE] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_ADD] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_SUB] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_MUL] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_DIV] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_MOD] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_BAND] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BOR] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BXOR] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE,
    [REDUCT_OPCODE_BNOT] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_SHL] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_SHR] = REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B |
        REDUCT_OPCODE_FLAG_READ_C,
    [REDUCT_OPCODE_JEQ] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
        REDUCT_OPCODE_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JNEQ] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
        REDUCT_OPCODE_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JLT] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
        REDUCT_OPCODE_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JLE] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
        REDUCT_OPCODE_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JGT] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
        REDUCT_OPCODE_FLAG_IS_SKIP,
    [REDUCT_OPCODE_JGE] = REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
        REDUCT_OPCODE_FLAG_IS_SKIP,
    [REDUCT_OPCODE_MOV_CONST] = reduct_opcode_flags[REDUCT_OPCODE_MOV],
    [REDUCT_OPCODE_CALL_CONST] = reduct_opcode_flags[REDUCT_OPCODE_CALL],
    [REDUCT_OPCODE_RET_CONST] = reduct_opcode_flags[REDUCT_OPCODE_RET],
    [REDUCT_OPCODE_CAPTURE_CONST] = reduct_opcode_flags[REDUCT_OPCODE_CAPTURE],
    [REDUCT_OPCODE_TAILCALL_CONST] = reduct_opcode_flags[REDUCT_OPCODE_TAILCALL],
    [REDUCT_OPCODE_EQ_CONST] = reduct_opcode_flags[REDUCT_OPCODE_EQ],
    [REDUCT_OPCODE_NEQ_CONST] = reduct_opcode_flags[REDUCT_OPCODE_NEQ],
    [REDUCT_OPCODE_LT_CONST] = reduct_opcode_flags[REDUCT_OPCODE_LT],
    [REDUCT_OPCODE_LE_CONST] = reduct_opcode_flags[REDUCT_OPCODE_LE],
    [REDUCT_OPCODE_GT_CONST] = reduct_opcode_flags[REDUCT_OPCODE_GT],
    [REDUCT_OPCODE_GE_CONST] = reduct_opcode_flags[REDUCT_OPCODE_GE],
    [REDUCT_OPCODE_ADD_CONST] = reduct_opcode_flags[REDUCT_OPCODE_ADD],
    [REDUCT_OPCODE_SUB_CONST] = reduct_opcode_flags[REDUCT_OPCODE_SUB],
    [REDUCT_OPCODE_MUL_CONST] = reduct_opcode_flags[REDUCT_OPCODE_MUL],
    [REDUCT_OPCODE_DIV_CONST] = reduct_opcode_flags[REDUCT_OPCODE_DIV],
    [REDUCT_OPCODE_MOD_CONST] = reduct_opcode_flags[REDUCT_OPCODE_MOD],
    [REDUCT_OPCODE_BAND_CONST] = reduct_opcode_flags[REDUCT_OPCODE_BAND],
    [REDUCT_OPCODE_BOR_CONST] = reduct_opcode_flags[REDUCT_OPCODE_BOR],
    [REDUCT_OPCODE_BXOR_CONST] = reduct_opcode_flags[REDUCT_OPCODE_BXOR],
    [REDUCT_OPCODE_BNOT_CONST] = reduct_opcode_flags[REDUCT_OPCODE_BNOT],
    [REDUCT_OPCODE_SHL_CONST] = reduct_opcode_flags[REDUCT_OPCODE_SHL],
    [REDUCT_OPCODE_SHR_CONST] = reduct_opcode_flags[REDUCT_OPCODE_SHR],
    [REDUCT_OPCODE_JEQ_CONST] = reduct_opcode_flags[REDUCT_OPCODE_JEQ],
    [REDUCT_OPCODE_JNEQ_CONST] = reduct_opcode_flags[REDUCT_OPCODE_JNEQ],
    [REDUCT_OPCODE_JLT_CONST] = reduct_opcode_flags[REDUCT_OPCODE_JLT],
    [REDUCT_OPCODE_JLE_CONST] = reduct_opcode_flags[REDUCT_OPCODE_JLE],
    [REDUCT_OPCODE_JGT_CONST] = reduct_opcode_flags[REDUCT_OPCODE_JGT],
    [REDUCT_OPCODE_JGE_CONST] = reduct_opcode_flags[REDUCT_OPCODE_JGE],
};
