#include <reduct/build.h>
#include <reduct/opcode.h>

#define FLAGS_UNA (REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_C)
#define FLAGS_BIN \
    (REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B | \
        REDUCT_OPCODE_FLAG_READ_C)
#define FLAGS_BIN_COM (FLAGS_BIN | REDUCT_OPCODE_FLAG_IS_COMMUTATIVE)
#define FLAGS_TER (FLAGS_BIN | REDUCT_OPCODE_FLAG_READ_A)
#define FLAGS_SKIP \
    (REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_B | REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_SKIP)
#define FLAGS_RNG (REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_RANGE)

const reduct_opcode_info_t reductOpcodeTable[128] = {
    [REDUCT_OPCODE_NOP] = {"NOP", REDUCT_OPCODE_LAYOUT_NONE, 0},
    [REDUCT_OPCODE_MOV] = {"MOV", REDUCT_OPCODE_LAYOUT_AC, FLAGS_UNA},
    [REDUCT_OPCODE_LIST] = {"LIST", REDUCT_OPCODE_LAYOUT_AB_RANGE,
        REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_RANGE},
    [REDUCT_OPCODE_CLOSURE] = {"CLOSURE", REDUCT_OPCODE_LAYOUT_AC,
        REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_C},
    [REDUCT_OPCODE_CAPTURE] = {"CAPTURE", REDUCT_OPCODE_LAYOUT_ABC_RANGE,
        REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_HAS_CONST},
    [REDUCT_OPCODE_JMP] = {"JMP", REDUCT_OPCODE_LAYOUT_SAX,
        REDUCT_OPCODE_FLAG_IS_JUMP | REDUCT_OPCODE_FLAG_IS_TERMINATOR},
    [REDUCT_OPCODE_JMPF] = {"JMPF", REDUCT_OPCODE_LAYOUT_SAXC,
        REDUCT_OPCODE_FLAG_IS_JUMP | REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_TERMINATOR},
    [REDUCT_OPCODE_JMPT] = {"JMPT", REDUCT_OPCODE_LAYOUT_SAXC,
        REDUCT_OPCODE_FLAG_IS_JUMP | REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_TERMINATOR},
    [REDUCT_OPCODE_CALL] = {"CALL", REDUCT_OPCODE_LAYOUT_ABC_RANGE,
        REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A |
            REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_READ_RANGE | REDUCT_OPCODE_FLAG_IS_CALL},
    [REDUCT_OPCODE_RET] = {"RET", REDUCT_OPCODE_LAYOUT_C,
        REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_IS_TERMINATOR},
    [REDUCT_OPCODE_TAILCALL] = {"TAILCALL", REDUCT_OPCODE_LAYOUT_ABC_RANGE,
        REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_C |
            REDUCT_OPCODE_FLAG_READ_RANGE | REDUCT_OPCODE_FLAG_IS_CALL | REDUCT_OPCODE_FLAG_IS_TERMINATOR},
    [REDUCT_OPCODE_RECUR] = {"RECUR", REDUCT_OPCODE_LAYOUT_AB_RANGE,
        REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_RANGE |
            REDUCT_OPCODE_FLAG_IS_CALL | REDUCT_OPCODE_FLAG_IS_RECUR},
    [REDUCT_OPCODE_TAILRECUR] = {"TAILRECUR", REDUCT_OPCODE_LAYOUT_AB_RANGE,
        REDUCT_OPCODE_FLAG_READ_A | REDUCT_OPCODE_FLAG_READ_RANGE | REDUCT_OPCODE_FLAG_IS_CALL |
            REDUCT_OPCODE_FLAG_IS_TERMINATOR | REDUCT_OPCODE_FLAG_IS_RECUR},
    [REDUCT_OPCODE_EQ] = {"EQ", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN_COM},
    [REDUCT_OPCODE_NEQ] = {"NEQ", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN_COM},
    [REDUCT_OPCODE_LT] = {"LT", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_LE] = {"LE", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_GT] = {"GT", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_GE] = {"GE", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_ADD] = {"ADD", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN_COM},
    [REDUCT_OPCODE_SUB] = {"SUB", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_MUL] = {"MUL", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN_COM},
    [REDUCT_OPCODE_DIV] = {"DIV", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_MOD] = {"MOD", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_BAND] = {"BAND", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN_COM},
    [REDUCT_OPCODE_BOR] = {"BOR", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN_COM},
    [REDUCT_OPCODE_BXOR] = {"BXOR", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN_COM},
    [REDUCT_OPCODE_BNOT] = {"BNOT", REDUCT_OPCODE_LAYOUT_AC, FLAGS_UNA},
    [REDUCT_OPCODE_SHL] = {"SHL", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_SHR] = {"SHR", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_BIN},
    [REDUCT_OPCODE_JEQ] = {"JEQ", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_SKIP},
    [REDUCT_OPCODE_JNEQ] = {"JNEQ", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_SKIP},
    [REDUCT_OPCODE_JLT] = {"JLT", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_SKIP},
    [REDUCT_OPCODE_JLE] = {"JLE", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_SKIP},
    [REDUCT_OPCODE_JGT] = {"JGT", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_SKIP},
    [REDUCT_OPCODE_JGE] = {"JGE", REDUCT_OPCODE_LAYOUT_ABC, FLAGS_SKIP},
    [REDUCT_OPCODE_FORK] = {"FORK", REDUCT_OPCODE_LAYOUT_ABC_RANGE,
        REDUCT_OPCODE_FLAG_HAS_TARGET | REDUCT_OPCODE_FLAG_HAS_CONST | REDUCT_OPCODE_FLAG_READ_A |
            REDUCT_OPCODE_FLAG_READ_C | REDUCT_OPCODE_FLAG_READ_RANGE | REDUCT_OPCODE_FLAG_IS_CALL |
            REDUCT_OPCODE_FLAG_IS_FORK},
    [REDUCT_OPCODE_JOIN] = {"JOIN", REDUCT_OPCODE_LAYOUT_AC, FLAGS_UNA},
};
